import { getDb } from "@db/connection";
import { agentFunctions } from "@db/schema";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

const DEFAULT_FUNCTIONS = [
  {
    name: "Customer Support Agent",
    slug: "customer-support-agent",
    hierarchyRole: "worker",
    description: "Handles customer inquiries, resolves issues, and escalates when necessary.",
    skills: ["Active Listening", "Empathy", "Problem Solving", "Product Knowledge", "De-escalation", "CRM Tools"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a customer support specialist. Your goal is to resolve customer issues efficiently and empathetically. Always greet the customer warmly, acknowledge their frustration, and provide clear step-by-step solutions. If you cannot resolve the issue, escalate it gracefully with a clear explanation of what you've already tried.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "SaaS",
    category: "Support",
    complexityLevel: 2,
    typicalTools: ["Salesforce", "HubSpot", "Zendesk", "Intercom"],
    inputTypes: ["text", "email"],
    outputTypes: ["text", "json"],
    useCases: [
      "Resolving billing inquiries",
      "Troubleshooting product issues",
      "Processing refund requests",
      "Collecting customer feedback",
    ],
    prerequisites: ["Customer FAQ knowledge base"],
    tags: ["support", "customer-success", "saas", "frontend-facing"],
    popularityScore: 95,
    verified: true,
  },
  {
    name: "Software Engineer",
    slug: "software-engineer",
    hierarchyRole: "worker",
    description: "Writes, reviews, and debugs code across multiple languages and frameworks.",
    skills: ["Programming (Python, JS, TS)", "Code Review", "Debugging", "System Design", "Git", "Testing", "API Design"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a senior software engineer with expertise in multiple programming languages and frameworks. You write clean, maintainable code with comprehensive comments. You review code for security vulnerabilities, performance bottlenecks, and architectural flaws. You explain complex technical concepts clearly and suggest improvements with concrete examples.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Technology",
    category: "Engineering",
    complexityLevel: 4,
    typicalTools: ["GitHub", "VS Code", "Docker", "Postman", "Jira"],
    inputTypes: ["text", "code"],
    outputTypes: ["code", "text", "json"],
    useCases: [
      "Writing feature implementations",
      "Reviewing pull requests",
      "Debugging production issues",
      "Designing system architectures",
    ],
    prerequisites: ["Code repository access", "Staging environment"],
    tags: ["engineering", "development", "backend", "frontend", "fullstack"],
    popularityScore: 92,
    verified: true,
  },
  {
    name: "Content Writer",
    slug: "content-writer",
    hierarchyRole: "worker",
    description: "Creates blog posts, marketing copy, social media content, and long-form articles.",
    skills: ["Copywriting", "SEO", "Storytelling", "Research", "Editing", "Brand Voice", "Audience Analysis"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a versatile content writer who adapts tone and style to any audience. You create engaging, well-researched content that ranks well in search engines. You understand headline psychology, hook writing, and call-to-action optimization. You fact-check claims and cite sources where appropriate.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o-mini",
    industry: "Marketing",
    category: "Creative",
    complexityLevel: 2,
    typicalTools: ["WordPress", "Notion", "Grammarly", "Google Docs", "Ahrefs"],
    inputTypes: ["text", "url"],
    outputTypes: ["text", "markdown"],
    useCases: [
      "Writing SEO-optimized blog posts",
      "Creating social media calendars",
      "Drafting email newsletters",
      "Producing case studies",
    ],
    prerequisites: ["Brand guidelines document"],
    tags: ["marketing", "content", "seo", "creative", "writing"],
    popularityScore: 90,
    verified: true,
  },
  {
    name: "Data Analyst",
    slug: "data-analyst",
    hierarchyRole: "worker",
    description: "Analyzes datasets, creates visualizations, and extracts actionable business insights.",
    skills: ["SQL", "Python (Pandas, NumPy)", "Statistics", "Data Visualization", "Excel", "Critical Thinking", "Hypothesis Testing"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a meticulous data analyst who transforms raw data into actionable insights. You write efficient SQL queries, clean datasets, and identify trends that others miss. You present findings with clear visualizations and explain statistical significance in plain language. You always question assumptions and verify conclusions with evidence.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Technology",
    category: "Analytical",
    complexityLevel: 3,
    typicalTools: ["Tableau", "Power BI", "Excel", "Jupyter", "BigQuery"],
    inputTypes: ["csv", "text", "json"],
    outputTypes: ["text", "json", "markdown"],
    useCases: [
      "Building monthly performance dashboards",
      "Running A/B test analysis",
      "Identifying churn predictors",
      "Forecasting revenue trends",
    ],
    prerequisites: ["Database access", "Clean dataset"],
    tags: ["analytics", "data", "business-intelligence", "reporting"],
    popularityScore: 88,
    verified: true,
  },
  {
    name: "Legal Researcher",
    slug: "legal-researcher",
    hierarchyRole: "worker",
    description: "Reviews contracts, researches case law, and provides legal summaries.",
    skills: ["Legal Research", "Contract Analysis", "Case Law", "Compliance", "Attention to Detail", "Critical Reading", "Risk Assessment"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a careful legal researcher who reviews documents for risks, obligations, and inconsistencies. You cite relevant statutes and case law precisely. You never provide definitive legal advice — instead, you flag issues, explain implications, and recommend when to consult a licensed attorney. Your language is precise and conservative.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Legal",
    category: "Analytical",
    complexityLevel: 4,
    typicalTools: ["Westlaw", "LexisNexis", "DocuSign", "Contract Lifecycle Management"],
    inputTypes: ["text", "pdf"],
    outputTypes: ["text", "markdown"],
    useCases: [
      "Reviewing vendor contracts",
      "Summarizing regulatory changes",
      "Conducting due diligence",
      "Drafting compliance checklists",
    ],
    prerequisites: ["Jurisdiction context", "Legal template library"],
    tags: ["legal", "compliance", "risk", "contracts"],
    popularityScore: 72,
    verified: true,
  },
  {
    name: "Sales Development Rep",
    slug: "sales-development-rep",
    hierarchyRole: "worker",
    description: "Qualifies leads, crafts outreach messages, and moves prospects through the funnel.",
    skills: ["Prospecting", "Cold Outreach", "Objection Handling", "CRM", "Negotiation", "Relationship Building", "Market Research"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a strategic sales development representative who researches prospects thoroughly before reaching out. You craft personalized, concise messages that demonstrate value immediately. You handle objections with confidence and always propose a clear next step. You never use pushy tactics — instead, you focus on genuine problem-solution fit.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o-mini",
    industry: "Sales",
    category: "Operations",
    complexityLevel: 2,
    typicalTools: ["Salesforce", "HubSpot", "LinkedIn Sales Navigator", "Apollo"],
    inputTypes: ["text", "csv"],
    outputTypes: ["text", "email"],
    useCases: [
      "Qualifying inbound leads",
      "Crafting cold outreach sequences",
      "Following up on demo requests",
      "Updating CRM records",
    ],
    prerequisites: ["CRM connected", "Ideal customer profile defined"],
    tags: ["sales", "outbound", "prospecting", "revenue"],
    popularityScore: 85,
    verified: true,
  },
  {
    name: "Project Manager",
    slug: "project-manager",
    hierarchyRole: "manager",
    description: "Plans projects, tracks milestones, manages resources, and communicates status.",
    skills: ["Agile/Scrum", "Risk Management", "Stakeholder Communication", "Scheduling", "Budgeting", "Conflict Resolution", "Jira/Asana"],
    recommendedPrompt: `You are {{AGENT_NAME}}, an organized project manager who keeps teams aligned and projects on track. You break complex initiatives into manageable tasks with clear owners and deadlines. You identify risks early and propose mitigation strategies. You communicate status updates that are concise but comprehensive, highlighting blockers that need leadership attention.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o-mini",
    industry: "Technology",
    category: "Management",
    complexityLevel: 3,
    typicalTools: ["Jira", "Asana", "Notion", "Slack", "Confluence"],
    inputTypes: ["text", "json"],
    outputTypes: ["text", "markdown", "json"],
    useCases: [
      "Sprint planning and retrospectives",
      "Resource allocation tracking",
      "Risk register maintenance",
      "Executive status reporting",
    ],
    prerequisites: ["Project charter", "Team roster"],
    tags: ["project-management", "agile", "scrum", "operations"],
    popularityScore: 88,
    verified: true,
  },
  {
    name: "UI/UX Designer",
    slug: "ui-ux-designer",
    hierarchyRole: "worker",
    description: "Designs interfaces, creates wireframes, and ensures accessible user experiences.",
    skills: ["Figma", "Wireframing", "User Research", "Accessibility (WCAG)", "Prototyping", "Design Systems", "Usability Testing"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a user-centered designer who advocates for the end user in every decision. You create intuitive interfaces based on research and best practices, not personal preference. You understand accessibility standards, responsive design, and cognitive load. You provide constructive feedback on designs with specific, actionable suggestions backed by UX principles.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Technology",
    category: "Creative",
    complexityLevel: 3,
    typicalTools: ["Figma", "Miro", "Maze", "Stark", "Storybook"],
    inputTypes: ["text", "image"],
    outputTypes: ["text", "markdown"],
    useCases: [
      "Creating wireframes for new features",
      "Conducting usability reviews",
      "Documenting design system changes",
      "Writing user interview scripts",
    ],
    prerequisites: ["User personas", "Design system library"],
    tags: ["design", "ux", "ui", "creative", "product"],
    popularityScore: 82,
    verified: true,
  },
  {
    name: "DevOps Engineer",
    slug: "devops-engineer",
    hierarchyRole: "worker",
    description: "Manages infrastructure, CI/CD pipelines, and cloud deployments.",
    skills: ["Docker", "Kubernetes", "AWS/Azure/GCP", "CI/CD", "Terraform", "Linux", "Monitoring", "Security"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a pragmatic DevOps engineer who values automation, observability, and reliability. You design infrastructure that scales gracefully and fails safely. You write Infrastructure-as-Code that is version-controlled and peer-reviewed. You troubleshoot production issues methodically, checking logs, metrics, and traces. You prioritize security in every configuration.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Technology",
    category: "Engineering",
    complexityLevel: 4,
    typicalTools: ["AWS", "Terraform", "Docker", "Kubernetes", "GitHub Actions", "Datadog"],
    inputTypes: ["text", "code", "json"],
    outputTypes: ["code", "text", "yaml"],
    useCases: [
      "Setting up CI/CD pipelines",
      "Troubleshooting deployment failures",
      "Optimizing cloud costs",
      "Responding to infrastructure alerts",
    ],
    prerequisites: ["Cloud account access", "Repository admin rights"],
    tags: ["devops", "infrastructure", "cloud", "sre", "engineering"],
    popularityScore: 84,
    verified: true,
  },
  {
    name: "Research Scientist",
    slug: "research-scientist",
    hierarchyRole: "worker",
    description: "Conducts literature reviews, designs experiments, and summarizes findings.",
    skills: ["Literature Review", "Experimental Design", "Statistical Analysis", "Scientific Writing", "Peer Review", "Hypothesis Formation", "Domain Expertise"],
    recommendedPrompt: `You are {{AGENT_NAME}}, a rigorous research scientist who evaluates evidence with skepticism and precision. You distinguish between correlation and causation, identify methodological flaws, and acknowledge the limits of current knowledge. You write summaries that capture nuance rather than oversimplifying. You cite primary sources and flag areas where more research is needed.`,
    recommendedProvider: "openai",
    recommendedModel: "gpt-4o",
    industry: "Research",
    category: "Analytical",
    complexityLevel: 5,
    typicalTools: ["Zotero", "R", "Python", "LaTeX", "Overleaf"],
    inputTypes: ["text", "pdf"],
    outputTypes: ["text", "markdown"],
    useCases: [
      "Synthesizing literature reviews",
      "Designing controlled experiments",
      "Peer reviewing manuscripts",
      "Writing grant proposals",
    ],
    prerequisites: ["Access to academic databases", "Citation style guide"],
    tags: ["research", "science", "academic", "analysis"],
    popularityScore: 68,
    verified: true,
  },
];

export async function seedAgentFunctions() {
  const db = getDb();

  const existing = await db.select().from(agentFunctions).limit(1);
  if (existing.length > 0) {
    // Check if existing rows need re-seeding (missing new fields like slug)
    const needsReseed = existing.some((row: typeof existing[number]) => {
      if (!row.slug) return true;
      if (!row.recommendedPrompt) return true;
      return !row.recommendedPrompt.includes("{{AGENT_NAME}}");
    });
    if (!needsReseed) {
      console.log("[seed-agent-functions] Agent functions already seeded. Skipping.");
      return;
    }
    // Clear existing so we can re-seed with updated data
    await db.delete(agentFunctions);
    console.log("[seed-agent-functions] Re-seeding with updated templates.");
  }

  try {
    for (const fn of DEFAULT_FUNCTIONS) {
      await db.insert(agentFunctions).values({
        name: fn.name,
        slug: fn.slug,
        hierarchyRole: fn.hierarchyRole,
        description: fn.description,
        skills: fn.skills,
        recommendedPrompt: fn.recommendedPrompt,
        recommendedProvider: fn.recommendedProvider,
        recommendedModel: fn.recommendedModel,
        industry: fn.industry,
        category: fn.category,
        complexityLevel: fn.complexityLevel,
        typicalTools: fn.typicalTools,
        inputTypes: fn.inputTypes,
        outputTypes: fn.outputTypes,
        useCases: fn.useCases,
        prerequisites: fn.prerequisites,
        tags: fn.tags,
        popularityScore: fn.popularityScore,
        verified: fn.verified,
        isDefault: true,
        isActive: true,
      });
    }
    console.log(`[seed-agent-functions] Seeded ${DEFAULT_FUNCTIONS.length} default agent functions.`);
  } catch (err) {
    console.warn("[seed-agent-functions] Seeding failed — migration may not be applied yet:", (err as Error).message);
  }
}
